version: "3.7"

services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - ./auth_service/.env-non-dev
    command: -p 5432

  auth_service:
    build:
      context: ./auth_service
    container_name: web_layer
    env_file:
      - ./auth_service/.env-non-dev
    ports:
      - 8001:8000
    command:
      sh -c "
      gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
