"""empty message

Revision ID: 31d5fb9a2c0d
Revises: 6e9bbb49fcc5
Create Date: 2024-08-02 07:06:54.069478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d5fb9a2c0d'
down_revision: Union[str, None] = '6e9bbb49fcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
