"""add relationship between playlist and music

Revision ID: 3b848d40d554
Revises: a8b7d037c923
Create Date: 2024-08-02 07:17:35.482353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision: str = '3b848d40d554'
down_revision: Union[str, None] = 'a8b7d037c923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute( "DELETE FROM music" )
    op.execute( "DELETE FROM play_list")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('playlist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'music', 'play_list', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.add_column('play_list', sa.Column('upload_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_list', 'upload_date')
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.drop_column('music', 'playlist_id')
    # ### end Alembic commands ###
