"""add photo_path

Revision ID: 6e9bbb49fcc5
Revises: f8307355e971
Create Date: 2024-08-01 09:14:40.727353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9bbb49fcc5'
down_revision: Union[str, None] = 'f8307355e971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('photo_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'photo_path')
    # ### end Alembic commands ###
