"""empty message

Revision ID: a8b7d037c923
Revises: 31d5fb9a2c0d
Create Date: 2024-08-02 07:09:02.726080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b7d037c923'
down_revision: Union[str, None] = '31d5fb9a2c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('play_list_music_id_fkey', 'play_list', type_='foreignkey')
    op.drop_column('play_list', 'music_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_list', sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('play_list_music_id_fkey', 'play_list', 'music', ['music_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
