"""empty message

Revision ID: aa6cabc1fd63
Revises: 923f9b12ecfd
Create Date: 2024-07-31 13:49:02.088539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6cabc1fd63'
down_revision: Union[str, None] = '923f9b12ecfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('music', sa.Column('album', sa.String(), nullable=True))
    op.add_column('music', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('music', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'file_path')
    op.drop_column('music', 'genre')
    op.drop_column('music', 'album')
    op.drop_column('music', 'artist')
    # ### end Alembic commands ###
