"""add user_id to playlist

Revision ID: fcf3137c5a8b
Revises: 8fadc905f40e
Create Date: 2024-08-02 07:52:59.098609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf3137c5a8b'
down_revision: Union[str, None] = '8fadc905f40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_list', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_list', 'user_id')
    # ### end Alembic commands ###
