"""empty message

Revision ID: fe0a431c808b
Revises: fcf3137c5a8b
Create Date: 2024-08-11 18:33:57.238329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0a431c808b'
down_revision: Union[str, None] = 'fcf3137c5a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute( "DELETE FROM music" )
    op.execute( "DELETE FROM play_list" )
    op.add_column('play_list', sa.Column('photo_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_list', 'photo_path')
    # ### end Alembic commands ###
